const express = require("express");
const router = express.Router();
const authController = require("../controllers/authController");
const authenticateToken = require("../middleware/authMiddleware");
router.post("/register", authController.register);
router.post("/login", authController.login);
router.post("/logout", authenticateToken, authController.logout);
router.get("/userInfo", authenticateToken, authController.UserInfo);
router.delete("/deleteUser/:id",authController.deleteUser);
router.get("/getAllUsers",authController.getAllUsers);
router.get('/orders/history/:userId', authController.getOrderHistory);
module.exports = router;
